### PR TITLE
[FEATURE] Initial support for ratelimits

### PR DESCRIPTION
**Pull request by lucasew**
FEATURE: Initial support for ratelimits

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Initial support for ratelimits using redis decr and my small amount of knowledge in javascript. I don't know really if this is the right way to make this but i tried to make something.

* **What is the current behavior?** (You can also link to an open issue here)
Check if login passes and send the message.

* **What is the new behavior (if this is a feature change)?**
Resolve the problem that is ratelimits in messages sent by the clients only if it is enabled.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
In theory just set environment variables to test and use the feature

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
Nothing found in a quick search

* **Other information**:
Latinoware

### CODE REVIEW

**Comment by giovannicuriel** [comment]
Hi!
Thank you in advance for taking some time to contribute!

I checked your code and looks good! I think that this might be a good first implementation of this feature. 

But we have a few considerations about this feature, though. For message quotas, what we thought as a basic scenario is this:
> There are many IoT agent instances receiving thousands of messages per second each. These messages are related to different devices which also are associated to different tenants.  A device might send its messages to a different IoT agent instance each time. 

What we are asking ourselves is: is there a method of precisely counting messages in order to block message reception once a limit is reached (for each device or tenant)? This should consider also failures (IoT agents may fail at any time) and horizontal scalability (we should be able to create new service instances of whatever solution we come up with).

We would like to avoid a centralized counter, which would create a bottleneck and it would be a single point of failure while processing these X thousands messages per second. For instance: what would happen if Redis crashes (or become unavailable for some reason)?

**Comment by lucas59356** [comment]
My idea is to use **decr** instead **incr** because of this, if the key doesn't exist its value is 0 that means request blocked. To fill the quota you need to set the key in redis with the remaining n messages and its decrements from n to 0, if the value of remaining is 0 the request is blocked. I am not sure  if this is the right way to do something like this in JS but I tried to forward the callback to the function that decrements the key and check if is >=0 and pass the result of the comparation to the callback.

About the redis server, that I don't know so much, i think that the master-slave can help, each kubernetes physical node run a redis instance that mirrors with the redis of others instance and the agent, reducing the network overhead. If the router have access to the destinations of the message if client id is >x forward to y route and this can maybe reduce the problem cause node x have more probability to process client x messages than client y. About indisponibilities redis have persistence via RDB and AOF like [this](https://redis.io/topics/persistence) page in the docs. I don't know if it's fits but it's a idea.

Here is redis-benchmark running in my machine, maybe on a network it doesn't run this fast. But in mine i5 7200U 6GB DDR4 it processes around 100k incr requests/s.

====== PING_INLINE ======
  100000 requests completed in 0.82 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

100.00% <= 0 milliseconds
121212.12 requests per second

====== PING_BULK ======
  100000 requests completed in 0.84 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

99.95% <= 1 milliseconds
100.00% <= 1 milliseconds
119189.52 requests per second

====== SET ======
  100000 requests completed in 0.81 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

99.97% <= 1 milliseconds
100.00% <= 1 milliseconds
122850.12 requests per second

====== GET ======
  100000 requests completed in 0.83 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

100.00% <= 0 milliseconds
120336.95 requests per second

====== INCR ======
  100000 requests completed in 0.84 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

100.00% <= 0 milliseconds
118483.41 requests per second

====== LPUSH ======
  100000 requests completed in 0.78 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

99.99% <= 1 milliseconds
100.00% <= 1 milliseconds
128040.97 requests per second

====== RPUSH ======
  100000 requests completed in 0.85 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

99.98% <= 1 milliseconds
100.00% <= 1 milliseconds
117233.30 requests per second

====== LPOP ======
  100000 requests completed in 0.80 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

99.97% <= 1 milliseconds
100.00% <= 1 milliseconds
124533.01 requests per second

====== RPOP ======
  100000 requests completed in 0.80 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

99.97% <= 1 milliseconds
100.00% <= 1 milliseconds
124533.01 requests per second

====== SADD ======
  100000 requests completed in 0.81 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

99.98% <= 1 milliseconds
100.00% <= 1 milliseconds
123762.38 requests per second

====== HSET ======
  100000 requests completed in 0.79 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

99.97% <= 1 milliseconds
100.00% <= 1 milliseconds
127388.53 requests per second

====== SPOP ======
  100000 requests completed in 0.85 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

99.98% <= 1 milliseconds
100.00% <= 1 milliseconds
117924.53 requests per second

====== LPUSH (needed to benchmark LRANGE) ======
  100000 requests completed in 0.82 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

99.97% <= 1 milliseconds
100.00% <= 1 milliseconds
122399.02 requests per second

====== LRANGE_100 (first 100 elements) ======
  100000 requests completed in 2.52 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

99.81% <= 1 milliseconds
100.00% <= 1 milliseconds
39682.54 requests per second

====== LRANGE_300 (first 300 elements) ======
  100000 requests completed in 6.03 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

0.01% <= 1 milliseconds
99.32% <= 2 milliseconds
99.92% <= 3 milliseconds
99.97% <= 4 milliseconds
100.00% <= 4 milliseconds
16594.76 requests per second

====== LRANGE_500 (first 450 elements) ======
  100000 requests completed in 8.34 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

0.00% <= 1 milliseconds
58.37% <= 2 milliseconds
99.88% <= 3 milliseconds
99.94% <= 4 milliseconds
99.98% <= 5 milliseconds
99.99% <= 6 milliseconds
100.00% <= 6 milliseconds
11987.53 requests per second

====== LRANGE_600 (first 600 elements) ======
  100000 requests completed in 10.68 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

0.00% <= 1 milliseconds
0.02% <= 2 milliseconds
91.30% <= 3 milliseconds
99.95% <= 4 milliseconds
99.97% <= 5 milliseconds
99.99% <= 6 milliseconds
100.00% <= 7 milliseconds
9365.93 requests per second

====== MSET (10 keys) ======
  100000 requests completed in 0.77 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

99.97% <= 1 milliseconds
100.00% <= 1 milliseconds
129198.97 requests per second

**Comment by giovannicuriel** [comment]
Hi! I'll change the destination branch to a feature branch, shall we? Therefore we can better test it before merge into master.

**Comment by lucasew** [comment]
> Hi! I'll change the destination branch to a feature branch, shall we? Therefore we can better test it before merge into master.
No problem, maybe someone more experienced than me can increment it and make it better.

**Pull request merged**
